name: Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Install base dependencies
        run: |
          pacman -Syu --noconfirm archlinux-keyring gcc make glibc gcc-libs vulkan-headers vulkan-utility-libraries
          pacman -Syu --noconfirm base-devel

          sudo pacman -Syu --noconfirm

      - name: Create build user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Fix permissions
        run: chown -R builder:builder .

      - name: Build & create release archive
        run: |
          sudo -u builder bash <<'EOF'
          set -e
          make
          mkdir release
          cp libNullVRS_layer.so release
          cp NullVRS_layer.json release
          cp README.md release
          cp LICENSE.txt release
          tar -czf "NullVRS_Linux_$(uname -m).tar.gz" -C ./release .
          EOF

      - name: Upload package artifact
        uses: actions/upload-artifact@v7
        with:
          name: NullVRS_Linux_x86_64.tar.gz
          path: |
            *.tar.gz
        archive: false
